In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('../Data/20220327 annual-number-of-deaths-by-cause.csv')
df

,Entity,Code,Year,Number of executions (Amnesty International),Deaths - Meningitis - Sex: Both - Age: All Ages (Number),Deaths - Neoplasms - Sex: Both - Age: All Ages (Number),"Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)",Deaths - Malaria - Sex: Both - Age: All Ages (Number),Deaths - Drowning - Sex: Both - Age: All Ages (Number),Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number),...,Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number),Terrorism (deaths),Deaths - Cardiovascular diseases - Sex: Both - Age: All Ages (Number),Deaths - Chronic kidney disease - Sex: Both - Age: All Ages (Number),Deaths - Chronic respiratory diseases - Sex: Both - Age: All Ages (Number),Deaths - Cirrhosis and other chronic liver diseases - Sex: Both - Age: All Ages (Number),Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number),Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number),Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number),Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)
0,Afghanistan,AFG,2007,15,2933.0,15925.0,481.0,393.0,2127.0,3657.0,...,2439.0,1199.0,53962.0,4490.0,7222.0,3346.0,6458.0,3437.0,1402.0,450.0
1,Afghanistan,AFG,2008,17,2731.0,16148.0,462.0,255.0,1973.0,3785.0,...,2231.0,1092.0,54051.0,4534.0,7143.0,3316.0,6408.0,3005.0,1424.0,455.0
2,Afghanistan,AFG,2009,0,2460.0,16383.0,448.0,239.0,1852.0,3874.0,...,1998.0,1065.0,53964.0,4597.0,7045.0,3291.0,6358.0,2663.0,1449.0,460.0
3,Afghanistan,AFG,2011,2,2327.0,17094.0,448.0,390.0,1775.0,4170.0,...,1805.0,1525.0,54347.0,4785.0,6916.0,3318.0,6370.0,2365.0,1508.0,473.0
4,Afghanistan,AFG,2012,14,2254.0,17522.0,445.0,94.0,1716.0,4245.0,...,1667.0,3521.0,54868.0,4846.0,6878.0,3353.0,6398.0,2264.0,1544.0,482.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8249,Zimbabwe,ZWE,2015,NaN,1439.0,11161.0,632.0,2518.0,770.0,1302.0,...,2990.0,NaN,16649.0,2108.0,2751.0,1956.0,4202.0,146.0,754.0,215.0
8250,Zimbabwe,ZWE,2016,NaN,1457.0,11465.0,648.0,2050.0,801.0,1342.0,...,3027.0,NaN,16937.0,2160.0,2788.0,1962.0,4264.0,146.0,767.0,219.0
8251,Zimbabwe,ZWE,2017,NaN,1460.0,11744.0,654.0,2116.0,818.0,1363.0,...,2962.0,0.0,17187.0,2196.0,2818.0,2007.0,4342.0,144.0,781.0,223.0
8252,Zimbabwe,ZWE,2018,NaN,1450.0,12038.0,657.0,2088.0,825.0,1396.0,...,2890.0,NaN,17460.0,2240.0,2849.0,2030.0,4377.0,139.0,795.0,227.0
8253,Zimbabwe,ZWE,2019,NaN,1450.0,12353.0,662.0,2068.0,827.0,1434.0,...,2855.0,NaN,17810.0,2292.0,2891.0,2065.0,4437.0,136.0,812.0,232.0

In [14]:
print(df.columns)
print(df.info())

Index(['Causes name', 'Causes Full Description', 'Death Numbers', 'Entity',
       'Code', 'Year'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201762 entries, 0 to 201761
Data columns (total 6 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Causes name              201762 non-null  object
 1   Causes Full Description  201762 non-null  object
 2   Death Numbers            190575 non-null  float64
 3   Entity                   201762 non-null  object
 4   Code                     200277 non-null  object
 5   Year                     201762 non-null  int64
dtypes: float64(1), int64(1), object(4)
memory usage: 9.2+ MB
None

In [11]:
df = pd.read_csv('../Data/20222703 Causes Of Death Clean Output V2.0.csv')

In [12]:
df

,Causes name,Causes Full Description,Death Numbers,Entity,Code,Year
0,Meningitis,Deaths - Meningitis - Sex: Both - Age: All Age...,2933.0,Afghanistan,AFG,2007
1,Neoplasms,Deaths - Neoplasms - Sex: Both - Age: All Ages...,15925.0,Afghanistan,AFG,2007
2,"Fire, heat, and hot substances","Deaths - Fire, heat, and hot substances - Sex:...",481.0,Afghanistan,AFG,2007
3,Malaria,Deaths - Malaria - Sex: Both - Age: All Ages (...,393.0,Afghanistan,AFG,2007
4,Drowning,Deaths - Drowning - Sex: Both - Age: All Ages ...,2127.0,Afghanistan,AFG,2007
...,...,...,...,...,...,...
201757,Digestive diseases,Deaths - Digestive diseases - Sex: Both - Age:...,4437.0,Zimbabwe,ZWE,2019
201758,Acute hepatitis,Deaths - Acute hepatitis - Sex: Both - Age: Al...,136.0,Zimbabwe,ZWE,2019
201759,Alzheimer's disease and other dementias,Deaths - Alzheimer's disease and other dementi...,812.0,Zimbabwe,ZWE,2019
201760,Parkinson's disease,Deaths - Parkinson's disease - Sex: Both - Age...,232.0,Zimbabwe,ZWE,2019
201761,Number of executions (Amnesty International),Deaths - Number of executions (Amnesty Interna...,NaN,Zimbabwe,ZWE,2019

In [13]:
print(df.columns)
print(df.info())

Index(['Causes name', 'Causes Full Description', 'Death Numbers', 'Entity',
       'Code', 'Year'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201762 entries, 0 to 201761
Data columns (total 6 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Causes name              201762 non-null  object
 1   Causes Full Description  201762 non-null  object
 2   Death Numbers            190575 non-null  float64
 3   Entity                   201762 non-null  object
 4   Code                     200277 non-null  object
 5   Year                     201762 non-null  int64
dtypes: float64(1), int64(1), object(4)
memory usage: 9.2+ MB
None